[2025-05-10 18:03:52,223] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:21:31,850] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-10 21:21:33,697] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:25:45,861] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-10 21:25:48,175] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:33:15,405] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-10 21:33:17,918] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:42:36,342] ERROR django.request (log): Internal Server Error: /bibliothecaire/gestion-des-medias/
Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 57, in _view_wrapper
    test_pass = test_func(request.user)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 80, in <lambda>
    lambda u: u.is_authenticated,
              ^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
    ~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
                           ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ~~~~~~~~~~~~~~~~~~~~~~^
        session_key=self.session_key, expire_date__gt=timezone.now()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
[2025-05-10 21:42:36,438] ERROR django.server (basehttp): "GET /bibliothecaire/gestion-des-medias/ HTTP/1.1" 500 145
[2025-05-10 21:42:59,189] ERROR django.request (log): Internal Server Error: /
Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\views.py", line 4, in homepage
    return render(request, 'homePage.html')
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
    ~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
                           ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ~~~~~~~~~~~~~~~~~~~~~~^
        session_key=self.session_key, expire_date__gt=timezone.now()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
[2025-05-10 21:42:59,253] ERROR django.server (basehttp): "GET / HTTP/1.1" 500 145
[2025-05-10 21:44:10,704] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-10 21:44:10,758] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-10 21:44:10,779] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-10 21:44:15,311] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-10 21:44:15,380] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-10 21:44:15,387] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-10 21:44:18,501] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-10 21:44:18,565] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-10 21:44:18,569] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-10 21:44:19,375] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-10 21:44:19,443] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-10 21:44:19,444] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-10 21:44:20,816] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-10 21:44:20,883] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-10 21:44:20,886] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-10 21:44:57,780] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:45:02,052] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-10 21:45:02,109] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-10 21:45:02,113] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-10 21:47:46,612] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-10 21:47:48,674] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:47:52,233] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-10 21:47:52,570] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 200 182
[2025-05-10 21:48:03,087] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-10 21:48:03,869] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-10 21:48:04,755] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-10 21:52:22,666] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-10 21:52:24,371] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:54:06,601] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-10 21:54:08,857] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:54:49,121] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-10 21:54:50,576] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-10 21:54:51,317] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-10 21:55:13,979] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-10 21:55:17,323] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-10 21:55:20,782] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-10 21:55:21,975] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-10 21:55:24,370] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:23:44,506] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:24:37,306] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:24:50,712] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:24:50,762] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:24:50,763] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:24:50,862] WARNING django.request (log): Not Found: /static/favicon.png
[2025-05-11 10:24:50,863] WARNING django.server (basehttp): "GET /static/favicon.png HTTP/1.1" 404 1074
[2025-05-11 10:31:46,092] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\urls.py changed, reloading.
[2025-05-11 10:31:47,278] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:32:00,979] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\urls.py changed, reloading.
[2025-05-11 10:32:02,201] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:32:06,093] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:32:06,131] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:32:06,133] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:32:08,219] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:32:08,249] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:32:08,250] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:32:09,613] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:32:09,648] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:32:09,649] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:32:36,115] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:32:40,149] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:32:40,198] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:32:40,200] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:38:46,083] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:38:46,125] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:38:46,126] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:38:46,127] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:38:46,460] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:38:46,506] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:38:46,513] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:38:46,514] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:38:46,516] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:39:43,166] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\urls.py changed, reloading.
[2025-05-11 10:39:44,207] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:39:45,120] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:39:45,121] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:39:45,286] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:39:45,287] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:39:45,382] WARNING django.request (log): Not Found: /static/favicon.png
[2025-05-11 10:39:45,384] WARNING django.server (basehttp): "GET /static/favicon.png HTTP/1.1" 404 1074
[2025-05-11 10:39:53,272] WARNING django.request (log): Not Found: /staticfiles/css/style.css
[2025-05-11 10:39:53,273] WARNING django.server (basehttp): "GET /staticfiles/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:39:53,315] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:39:53,316] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:42:58,974] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:42:59,004] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:42:59,009] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:42:59,030] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:42:59,035] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:44:06,992] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:44:09,851] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:44:09,875] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:44:09,893] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:44:09,898] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:44:09,900] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:44:11,074] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:44:11,113] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:44:11,127] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:44:11,130] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:44:11,132] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:45:00,463] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 10:45:01,919] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:45:02,382] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1061
[2025-05-11 10:45:02,426] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:45:02,442] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1084
[2025-05-11 10:45:02,452] WARNING django.request (log): Not Found: /staticfiles/css/style.css
[2025-05-11 10:45:02,454] WARNING django.server (basehttp): "GET /staticfiles/css/style.css HTTP/1.1" 404 1084
[2025-05-11 10:45:02,505] WARNING django.request (log): Not Found: /staticfiles/favicon.png
[2025-05-11 10:45:02,506] WARNING django.server (basehttp): "GET /staticfiles/favicon.png HTTP/1.1" 404 1084
[2025-05-11 10:45:05,652] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1061
[2025-05-11 10:45:05,833] WARNING django.request (log): Not Found: /staticfiles/css/style.css
[2025-05-11 10:45:05,856] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:45:05,857] WARNING django.server (basehttp): "GET /staticfiles/css/style.css HTTP/1.1" 404 1084
[2025-05-11 10:45:05,877] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1084
[2025-05-11 10:45:38,125] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 10:45:39,354] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:45:39,723] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:45:39,764] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:45:39,772] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:45:39,774] INFO django.server (basehttp): - Broken pipe from ('127.0.0.1', 50933)
[2025-05-11 10:45:39,947] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:45:39,949] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:46:26,879] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:46:31,296] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:46:31,325] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:46:31,334] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:46:31,341] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:46:31,351] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:49:10,661] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 10:49:11,716] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:49:16,720] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:49:16,755] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:49:16,770] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:49:16,777] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:49:16,781] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:49:50,859] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:49:50,860] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:49:50,910] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:49:50,926] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:56:40,115] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 10:56:41,760] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:56:43,221] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 200 182
[2025-05-11 10:56:43,333] WARNING django.request (log): Not Found: /favicon.ico
[2025-05-11 10:56:43,334] WARNING django.server (basehttp): "GET /favicon.ico HTTP/1.1" 404 2687
[2025-05-11 10:56:48,304] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:56:48,358] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:56:48,360] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 200 182
[2025-05-11 10:56:48,361] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2798
[2025-05-11 10:57:04,804] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-11 10:57:04,865] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:57:04,867] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2798
[2025-05-11 10:57:04,868] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 200 1670
[2025-05-11 10:57:07,183] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:57:07,245] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:57:07,250] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2798
[2025-05-11 10:57:24,288] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 10:57:25,655] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 10:57:26,032] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:57:26,075] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:57:26,079] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:57:29,553] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 10:57:29,593] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 10:57:29,601] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:57:29,604] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 10:57:29,607] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:57:39,261] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:57:39,262] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 10:57:39,526] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 10:57:39,995] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:03:44,682] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\urls.py changed, reloading.
[2025-05-11 11:03:46,183] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 11:03:47,065] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:03:47,111] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:03:47,113] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:03:47,117] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:03:47,119] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:00,369] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 11:05:05,897] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:05:05,932] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:05,940] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:05,945] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:05,946] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:08,908] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:05:08,935] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:08,950] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:08,965] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:08,962] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:08,972] INFO django.server (basehttp): - Broken pipe from ('127.0.0.1', 51548)
[2025-05-11 11:05:10,019] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-11 11:05:10,061] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:10,076] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:10,079] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:10,081] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:10,088] WARNING django.request (log): Not Found: /static/js/medias_list.js
[2025-05-11 11:05:10,096] WARNING django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 404 1074
[2025-05-11 11:05:11,232] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-11 11:05:11,283] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:11,297] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:11,304] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:11,307] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:11,972] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:05:12,031] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:12,045] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:12,047] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:12,050] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:12,680] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-11 11:05:12,722] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:12,735] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:12,739] WARNING django.request (log): Not Found: /static/js/medias_list.js
[2025-05-11 11:05:12,740] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:12,744] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:12,747] WARNING django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 404 1074
[2025-05-11 11:05:19,002] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:05:19,057] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:19,063] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:19,064] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:19,064] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:20,109] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-11 11:05:20,150] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:20,167] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:20,170] WARNING django.request (log): Not Found: /static/js/medias_list.js
[2025-05-11 11:05:20,172] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:20,174] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:20,176] WARNING django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 404 1074
[2025-05-11 11:05:21,497] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-11 11:05:21,560] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:21,571] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:21,580] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:21,582] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:23,669] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-11 11:05:23,716] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:23,720] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:23,722] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:23,725] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:25,060] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-11 11:05:25,110] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:25,128] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:25,131] WARNING django.request (log): Not Found: /static/js/medias_list.js
[2025-05-11 11:05:25,135] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:25,148] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:05:25,159] WARNING django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 404 1074
[2025-05-11 11:05:36,596] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:05:36,646] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:05:36,652] WARNING django.request (log): Not Found: /static/css/style.css
[2025-05-11 11:05:36,674] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:05:36,677] WARNING django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 404 1074
[2025-05-11 11:08:39,456] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 11:08:40,638] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 11:08:53,908] INFO django.utils.autoreload (autoreload): C:\Fabien Acer\Etude\Informatique\CEF\zone_de_travail\devoirs_appliques\11_poo_python\mediatheque\CEF_devoirs_mediatheque\mediatheque_app\settings.py changed, reloading.
[2025-05-11 11:08:55,042] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 11:12:35,941] INFO django.utils.autoreload (autoreload): Watching for file changes with StatReloader
[2025-05-11 11:12:39,953] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:12:40,000] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:12:40,013] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:12:40,023] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 200 182
[2025-05-11 11:12:42,386] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5139
[2025-05-11 11:12:42,425] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:12:42,428] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:12:42,442] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 200 1670
[2025-05-11 11:12:55,849] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1051
[2025-05-11 11:12:55,906] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:12:55,915] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:14:09,022] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 200 182
[2025-05-11 11:14:10,105] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 11:14:10,791] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 11:14:13,771] WARNING django.request (log): Not Found: /static/css/style.cs
[2025-05-11 11:14:13,772] WARNING django.server (basehttp): "GET /static/css/style.cs HTTP/1.1" 404 1074
[2025-05-11 11:14:13,811] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 11:15:03,205] WARNING django.request (log): Not Found: /static/js/mediasList.js
[2025-05-11 11:15:03,207] WARNING django.server (basehttp): "GET /static/js/mediasList.js HTTP/1.1" 404 1074
[2025-05-11 11:15:17,980] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 304 0
[2025-05-11 11:22:51,422] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-11 11:22:51,460] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:22:51,461] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:22:51,470] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 11:23:05,396] INFO django.server (basehttp): "POST /bibliothecaire/connexion/ HTTP/1.1" 200 1726
[2025-05-11 11:23:05,445] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:23:05,453] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 11:23:13,803] INFO django.server (basehttp): "POST /bibliothecaire/connexion/ HTTP/1.1" 302 0
[2025-05-11 11:23:13,820] INFO django.server (basehttp): "GET / HTTP/1.1" 200 1685
[2025-05-11 11:23:13,873] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:23:13,877] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1708
[2025-05-11 11:23:14,974] INFO django.server (basehttp): "GET /bibliothecaire/gestion-des-membres/ HTTP/1.1" 200 5373
[2025-05-11 11:23:15,025] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:23:15,029] INFO django.server (basehttp): "GET /static/js/member_detail.js HTTP/1.1" 200 4036
[2025-05-11 11:23:15,035] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1708
[2025-05-11 11:23:15,665] INFO django.server (basehttp): "GET /bibliothecaire/gestion-des-medias/ HTTP/1.1" 200 9665
[2025-05-11 11:23:15,734] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:23:15,737] INFO django.server (basehttp): "GET /static/js/media_detail.js HTTP/1.1" 200 2590
[2025-05-11 11:23:15,748] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1708
[2025-05-11 11:23:15,783] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 304 0
[2025-05-11 11:38:31,276] INFO django.server (basehttp): "POST /bibliothecaire/gestion-des-medias/ HTTP/1.1" 302 0
[2025-05-11 11:38:31,333] INFO django.server (basehttp): "GET /bibliothecaire/gestion-des-medias/?success=create_media HTTP/1.1" 200 10021
[2025-05-11 11:38:31,397] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:38:31,398] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1708
[2025-05-11 11:38:31,405] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 11:38:31,410] INFO django.server (basehttp): "GET /static/js/media_detail.js HTTP/1.1" 304 0
[2025-05-11 11:38:31,434] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 304 0
[2025-05-11 11:43:31,094] INFO django.server (basehttp): "GET /bibliothecaire/gestion-des-medias/ HTTP/1.1" 200 9950
[2025-05-11 11:43:31,152] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 11:43:31,154] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1708
[2025-05-11 11:43:31,158] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 11:43:31,162] INFO django.server (basehttp): "GET /static/js/media_detail.js HTTP/1.1" 304 0
[2025-05-11 11:43:31,187] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 304 0
[2025-05-11 14:32:01,327] INFO django.server (basehttp): "GET /membres/nos-medias/ HTTP/1.1" 200 5388
[2025-05-11 14:32:01,372] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 14:32:01,388] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
[2025-05-11 14:32:01,392] INFO django.server (basehttp): "GET /static/css/style.css HTTP/1.1" 304 0
[2025-05-11 14:32:01,396] INFO django.server (basehttp): "GET /static/js/medias_list.js HTTP/1.1" 304 0
[2025-05-11 14:32:02,431] INFO django.server (basehttp): "GET /bibliothecaire/connexion/ HTTP/1.1" 200 1619
[2025-05-11 14:32:02,473] WARNING django.request (log): Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-05-11 14:32:02,475] WARNING django.server (basehttp): "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 1074
